# Generated by Django 2.2.1 on 2019-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('author_posts', models.ManyToManyField(to='estate.Post')),
            ],
            options={
                'ordering': ('agency_name',),
            },
        ),
    ]
