# Generated by Django 2.2.1 on 2019-05-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_auto_20190503_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agency_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='author_post',
        ),
        migrations.AddField(
            model_name='post',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='posts', to='estate.Agency'),
        ),
    ]
